import { GoogleGenerativeAI } from "@google/generative-ai";
import { createClient } from "@supabase/supabase-js";
import { v4 as uuidv4 } from 'uuid';

export async function generateQuestions(topic, session_code, userId = null) {
  // Validate environment variables - support both REACT_APP_ and direct naming for Vercel
  const geminiApiKey = process.env.GEMINI_API_KEY || process.env.REACT_APP_GEMINI_API_KEY;
  const supabaseUrl = process.env.SUPABASE_URL || process.env.REACT_APP_SUPABASE_URL;
  const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY || process.env.REACT_APP_SUPABASE_SERVICE_KEY;

  if (!geminiApiKey) {
    throw new Error('GEMINI_API_KEY environment variable is required');
  }
  if (!supabaseUrl) {
    throw new Error('SUPABASE_URL environment variable is required');
  }
  if (!supabaseServiceKey) {
    throw new Error('SUPABASE_SERVICE_KEY environment variable is required');
  }

  const genAI = new GoogleGenerativeAI(geminiApiKey);
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });

  const prompt = `
    Generate 10 multiple choice (MCQ) quiz questions on the topic "${topic}".
    Each question MUST have:
      - a question string
      - 4 options (A, B, C, D)
      - correct_answers: an array with ONE 0-based integer index of the correct option (e.g., [2] for option C)
    Example: { "question": "What is the capital of France?", "options": ["Berlin", "London", "Paris", "Madrid"], "correct_answers": [2] }
    
    Format your response as a JSON array of 10 objects, each matching the example above. Return only the JSON array, with no explanations, notes, or extra text. If you cannot provide a correct_answers array for a question, do not include that question.
  `;

  const result = await model.generateContent(prompt);
  const text = result.response.text();

  let cleaned = text.trim();
  // Remove Markdown code block if present
  if (cleaned.startsWith("```json")) {
    cleaned = cleaned.replace(/^```json/, "").replace(/```$/, "").trim();
  } else if (cleaned.startsWith("```")) {
    cleaned = cleaned.replace(/^```/, "").replace(/```$/, "").trim();
  }
  // Extract only the first JSON array (ignore any trailing notes)
  const firstBracket = cleaned.indexOf('[');
  const lastBracket = cleaned.lastIndexOf(']');
  if (firstBracket !== -1 && lastBracket !== -1) {
    cleaned = cleaned.substring(firstBracket, lastBracket + 1);
  }
  let questions;
  try {
    questions = JSON.parse(cleaned);
  } catch (e) {
    throw new Error("Gemini response was not valid JSON:\n" + text);
  }

  // Validate and flatten MCQ questions
  const quiz_id = uuidv4();
  const insertData = [];
  let slide_index = 0;
  if (Array.isArray(questions)) {
    for (const q of questions) {
      if (!q.question || !Array.isArray(q.options) || q.options.length !== 4 || !Array.isArray(q.correct_answers) || q.correct_answers.length !== 1 || typeof q.correct_answers[0] !== 'number' || q.correct_answers[0] < 0 || q.correct_answers[0] > 3) continue;
      insertData.push({
        id: crypto.randomUUID(),
        quiz_id,
        slide_index: slide_index++,
        question: q.question,
        type: 'multiple',
        options: q.options,
        correct_answers: q.correct_answers,
        background: '#ffffff',
        text_color: '#000000',
        font_size: 20,
        font_family: 'Inter, Arial, sans-serif',
        created_at: new Date().toISOString(),
      });
    }
  }

  // Create the quiz record
  const { data: quizData, error: quizError } = await supabase
    .from('quizzes')
    .insert([{
      id: quiz_id,
      user_id: userId, // pass the user id if available, else null
      title: `AI Generated: ${topic}`,
      created_at: new Date().toISOString(),
      description: `Quiz generated by AI on the topic: ${topic}`,
      customization_settings: {
        fontFamily: 'Inter, Arial, sans-serif',
        textColor: '#000000',
        background: '#ffffff',
      },
      is_active: true,
      is_shared: false,
      is_published: false,
      created_by: 'ai_generated',
      current_slide_index: 0,
      mode: 'static',
      form_id: null,
      start_time: null,
      end_time: null
    }])
    .select()
    .single();

  if (quizError) throw new Error(`Failed to create quiz: ${quizError.message}`);

  const { error } = await supabase.from("slides").insert(insertData);
  if (error) throw new Error(error.message);

  return insertData;
} 